fgosc/fgosccalc

.gitignore, img2str.py
いくつか小さい不具合を修正しました。
f146ce2 だけはソースコードの読解が十分でなく ad hoc な対応であるため、これで良いか自信なしです。
=> Fix tiny bugs

calctweet.py, img2str.py
・任意の解像度対応
・トリミングされた画像の対応
・4枚の画像が周回前後の2組の報告の場合の合算に対応
=> 任意の解像度とトリミングされた画像への対応

img2str.py
=> Adapted to the party screen

img2str.py
=> fix #21 #23

main.py, views/result.tpl
=> 解析エラーでresultが正しく生成できなかった場合の画面表示を実装。

main.py, static/index.html
=> アップロード時ダイアログでの拡張子フィルター、およびサーバーサイドでの空ファイル対策。

README_dev.md
JS のプリコンパイルが必要になるなど、準備のタスクが増えたのでドキュメントにした。
=> 開発者向けドキュメント: ローカルでの web サーバーの立ち上げについて記述。

img2str.py
場所名、正しくはplaceなのにquestになっていたのを修正
=> 出力がquestになっていたのを修正

main.py
=> make_diff がリスト内のオブジェクトに対して破壊的操作を行うため deepcopy を渡す。

fgosccalc.py, img2str.py
1. 北米の周回場所表示がchapter+ placeになっていた
2. img2strのコピーをdeepcopyにして元を変更しないように
=> 北米の周回場所表示バグ img2strのコピーをdeepcopyに

fgosccalc.py
=> 礼装NaNが無くなるバグ修正

img2str.py
周回場所が判定できているにも関わらず判定できないとでるバグをfix
=> 周回場所が判定できないとでるバグfix

calctweet.py, hash_drop.json, img2str.py
- セイバーウォーズ2の銅のセイバーバッヂの画像の距離が実際の画像より遠い問題の解決
- 冬木X-Aが冬木X-Gと誤認識される問題の解決
- shortnameが無いとKeyErrorが発生する問題の解決
- 認識外アイテムが正常に処理されなくなっていた問題の解決
=> 様々な細かいバグフィックス

fgosccalc.py, img2str.py, main.py
=> Issue #79 の修正

static/js/src/report.jsx
=> 周回外増減の表現がわかりにくいので「消費」「追加獲得」に改める。

data/json/valentine2018.json, hash_drop.json, img2str.py
- #86 の修正
- バレンタイン2018のデータを入れた
=> Issue #86 の修正

.gcloudignore
=> /data/json/ はデプロイ対象。

fgosccalc.py
=> -oオプション無しのときに TypeErrorがでる不具合の修正

fgosccalc.py
画像不明だが誤認識したときにValueErrorとなり落ちるのを修正
=> 誤認識時にValueErrorを修正

fgosccalc.py
=> スクロールがずれた追加アイテムの誤認識バグ修正

fgosccalc.py
誤検出するのは上部か下部と割り切って、リストの真ん中の面積と離れたやつをカット
=> 所持アイテム座標誤認識の修正

fgosccalc.py, img2str.py
fgosccnt.py sc1 sc2
というコマンドだったのを
fgosccnt.py -b sc1 -a sc2
と変更 -b, -a には二つまでファイルを入力でき、スクロール上下の順番は問わない(自動認識)
=> スクロールした2枚のスクリーンショット対応

fgosccalc.py
twitterに画像をアップロードしてそれをURLとして挿入する機能の追加
=> Tweet post add

Makefile
=> master を最新にして submodule を更新する一覧の手続きを make で実行可能にする。

img2str.py
img2stry.py にfgoscdataのクエスト名追加にそのまま使用できる csv 出力機能を追加した
また、基本 logging でデバッグ用の出力をするようにした
**次のオプションを追加**
```
--csv                 fgoscdata用csv形式で出力
-q QUESTID, --questid QUESTID
```
QUESTIDを指定することで、id,クエスト名、shortnameも自動で埋まったcsvを出力する
```
$ python img2str.py test.jpg  -q 94051725 --csv
,サイレントガーデン,サイレントガーデン,ハイド・ハンター,胆石,髄液,弓魔,弓輝,チェーンソー,薪,所持数無しアイテム
```
=> add img2str csv output

dropitemseditor.py
=> Syoji item fix

dropitemseditor.py, img2str.py
background 属性を加えたことによるOwned itemのエンバグを修正
=> Owned item 認識バグ

dropitemseditor.py, fgosccalc.py, img2str.py, main.py
=> reduce EMD

.github/workflows/deploy.yml
=> デプロイ用 github workflow を追加。

.github/workflows/deploy.yml
=> インデントが壊れているのを修正。

.github/workflows/deploy.yml
=> actions/gcloud/cli は古いため Google が提供するモジュールを使う。

.github/workflows/deploy.yml
=> コンテナビルド前のライブラリセットアップ手順が抜けているのを修正。

.github/workflows/deploy.yml
=> input variables を修正。

.github/workflows/deploy.yml
=> 空のディレクトリはデプロイされないらしい。空ファイルを追加する。

main.py, views/error.tpl
8ea90761e と同等の変更を web 版にも適用したもの。
=> 周回と関係ない画像をアップするとエラーが起きる問題を修正。

main.py, static/index.html, views/result.tpl
=> スクロールが必要な戦利品画像をアップロード可能にする。

static/style.css, views/result.tpl
画像が side-by-side のとき、拡大可能にする。
このような場合に、それぞれの画像をクリックすると
こうなる。
width が小さく画像が横いっぱいになっているときは拡大不可（というか、する必要がない）。
=> side-by-side のとき画像を拡大可能にする。

dropitemseditor.py, fgosccalc.py, main.py
ScrollPositionErrorの例外を発生して補足する
=> 周回前後をスクロール上下として食わせたときのエラー回避

dropitemseditor.py, main.py, static/index.html, static/loading.css, static/style.css, views/result.tpl
=> クライアントサイドで事前にJPEG変換してからサーバーに送信する。

dropitemseditor.py, fgosccalc.py, main.py, static/js/src/report.jsx, views/result.tpl
=> Select add

static/js/src/report.jsx, views/result.tpl
=> 周回場所候補選択UI改善

dropitemseditor.py
https://twitter.com/mymynya/status/1330099154660577283
が(トリミングされた)所持アイテムでValueErrorになる対策
=> トリミングして下部カットした画像対策

.dockerignore, .gcloudignore, .github/workflows/cloudrun.yml, Dockerfile, Makefile, main.py, requirements-docker.txt
GitHub Actions に認識させるためいったんマージする。
=> Cloud Run 対応

.github/workflows/cloudrun_prod.yml, .github/workflows/cloudrun_stg.yml
stg/prod を入力させる方法だと面倒そうなので、ファイル自体を別々にする。
=> stg/prod で yml を分ける。

.dockerignore, .gcloudignore, .github/workflows/appengine.yml, .github/workflows/cloudrun_prod.yml, .github/workflows/cloudrun_stg.yml, Dockerfile
=> Docker コンテナビルド時に JS のビルドをしていない問題を修正。

static/js/src/report.jsx
=> 序破級クエスト時に追加出現率%を出力

package-lock.json, static/js/src/report.jsx
デフォルトの周回場所で誤って投稿してしまうのを防ぐ。
状況次第でユーザーにとっては一手間増えることになるが、投稿ミスの発生を防ぐ方が重要であると判断。
=> クエストの候補が複数ある場合は周回場所をプリセットせず、明示的にユーザーが選択することを強制するUIに変更。

static/js/src/report.jsx
https://twitter.com/naoya_fgo708/status/1432362936652099588
=> 序破急の文字が末尾以外に来た場合でも追加出現率の表記が発生してしまう問題を修正。

.github/workflows/cloudrun_prod.yml, .github/workflows/cloudrun_stg.yml
=> deploy する region を明示する。

static/js/src/report.jsx
=> クエスト名でなくドロップ素材で追加ドロップ率表記の有無を決める。

dropitemseditor.py, main.py, static/js/src/report.jsx
- 報告値が3の倍数のときのみ。
- 直接入力モードに移行した場合、変換処理は無効になる。
=> 報告時にx3変換するオプションを追加。

static/js/src/report.jsx
=> スマホ縦画面の場合に編集画面を横スクロール可能にする。

poetry.lock, requirements-docker.txt, static/js/src/report.jsx
=> 消費/追加獲得の素材名末尾に (x3) のような枠表記がある場合、これを無視する。 

static/js/src/report.jsx
=> 事件簿フリクエの追加出現率表記に対応。

img2str.py
iPhoneSE(初代)で認識できるよう閾値を変更
#183 のための修正
=> iPhoneSE(初代)の認識修正

static/js/src/report.jsx
=> 礼装による素材のドロップ率上昇を報告フォーマットに組み入れる。

static/js/src/report.jsx
=> 泥率Up対象に骨を追加。

static/js/src/report.jsx
=> 泥率Up素材を更新。

static/js/src/report.jsx
https://news.fate-go.jp/2022/advanced_quest4/
=> update drop rate up materials

package-lock.json
jsx -> js の変換でしか使っていないので重要度は低いが、いちおう更新。
=> update npm modules

static/js/src/report.jsx
=> add new drop-rate-up materials

static/js/src/report.jsx
=> 涙石, 髄液を追加。

static/js/src/report.jsx
https://twitter.com/shoppo_fgo/status/1557663668959350784
https://twitter.com/shoppo_fgo/status/1557662966795108352
=> x3 変換の足切り条件を緩和。

static/js/src/report.jsx
=> ドロップ率アップ対象素材を更新: 鉄杭, 鎖

package-lock.json, package.json, static/js/src/report.jsx
=> 特定のイベントアイテムについては x3 変換を無効にする。

static/js/src/report.jsx
=> ドロップ率アップ素材: 種、毒針を追加

static/js/src/report.jsx
=> add 逆鱗, 勲章

static/js/src/report.jsx
いったん stgcalc にデプロイします。
投稿サイトの立ち上げのタイミングでマージ、本番リリースを想定。
=> Twitter 投稿を廃止 / fgo-drop-reporter との接続

static/js/src/report.jsx
=> 泥率Up礼装追加: 根

static/js/src/report.jsx
ハッシュタグ #FGO_1H_run を報告コメント欄に挿入します。
=> FGO_1H_run 支援機能
