fgosc/fgosccalc

calctweet.py, img2str.py
以下の機能を追加
--auto オプションでAPIで検索可能な #FGO周回カウンタ タグを全て取得
--reume オプションで前回取得したツイートの続きから開始
=> Calctweetに-a -r オプションを追加

.gitignore, img2str.py, storage/__init__.py, storage/filesystem.py, storage/test_filesystem.py
既存の `Item_dir` に対する操作を以下のように抽象化しました。
- 「アイテムディレクトリ内のアイテム一覧を取得する処理」を抽象化して「ストレージが持つアイテム一覧を返す」にしました。 `storage.Storage` クラスの `known_item_dict(self)` メソッドがこれに対応。
- 「未知のアイテムに新しいファイル名 (例 `item000001.png`) を与えて保存する処理」を抽象化して「未知のアイテムをストレージに登録する」にしました。 `storage.Storage` クラスの `create_item(self, im)` メソッドがこれに対応。
具体的な実装として `storage.FileSystemStorage` を用意しました。これを用いて、既存ソフトウェアの動作を壊さずに Storage の概念を導入します。今後は `storage.Storage` が定める規約 (`known_item_dict` と `create_item` メソッドを実装すること) に従う限り、新しい `storage.Storage` クラスの実装を追加していくことができます。
=> アイテムリストのストレージを抽象化する。

img2str.py
`"False"` は False として評価されないため、常にデバッグが有効になります。
この問題を修正します。
```
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> if not "False": print("ok")
...
>>> if not False: print("ok")
...
ok
>>>
```
=> デフォルトで debug が有効になってしまう問題を修正。

fgosccalc.py
新実装の検証が十分でないため、旧実装は引き続き残してあります。
実行時オプションで `--future` を与えると、新実装によるFGO周回カウンタ形式変換処理が実行されます。このオプションを与えない場合は旧実装が使われます。
=> ドロップをFGO周回カウンタ形式に変換する処理を再実装。

fgosccalc.py
未ドロップがあると周回場所が特定できない(仕様)、そして周回前スクショは周回後より未ドロップが多い
周回後のスクショで判明している場合はそれを採用する
周回前と周回後で違う場所を示している場合は採用しない
=> 周回後のスクショのみ周回場所が判明している場合それを採用する修正

img2str.py
- 秘石がクラス判別を誤認するので魔石・輝石同様クラス判別するようにした
- 秘石・魔石・輝石のハッシュ値をfgosccntと同じものにした
- これによって共通のハッシュ値を保守すればよくなった
=> fix gem hash

fgosccalc.py
1. 所持数無しアイテムが周回前未ドロップ・周回後ドロップのとき、周回前後の画像を逆に認識させるとKeyError: -1になる問題を修正
2. 周回前未ドロップ・周回後未ドロップのときKeyError: -1になる問題を修正
=> 所持数無しアイテムのエラー修正

Makefile, static/js/src/report.jsx
現在の設定では、ベータサイトURLであっても実体は本番サイトになっている。そこで、ツイートボタンによるツイートのときに強制挿入されるURLが本番サイトのものであれば、実質的に本番サイトを利用しているのと同じことになる。この修正でそれを達成する。
=> ツイート時に挿入されるURLが常に fgosccalc.appspot.com になるようにする。

main.py
fixes #77
スマホサイズの画像（特に iPhone6/7/8 のような解像度があまり高くないもの）をリサイズすると小さくなりすぎるため、縦が1000pxを超えるものをリサイズすることにする。あわせて出力は常に jpg とする。
=> 保存形式を jpg にして、かつ解像度の高い画像はリサイズする。これで画像サイズを 500kb 以下にできる。

data/json/cbc2019.json, data/json/cbc2020.json, data/json/valentine2019.json, data/json/valentine2020.json, fgosccalc.py, hash_drop.json, img2str.py
1. 現時点で[未復刻イベント一覧](https://gamewith.jp/fgo/article/show/154578)にでているバトルリザルトのスクショが必要になるイベントは「激闘！クラス別サーヴァント戦」を除き収録した
2. クエスト名が判別されていて、かつ周回前後で礼装がドロップしていない場合、礼装NaNではなく礼装0と出力するようにした
=> 未復刻イベント対応と礼装が周回前後未ドロップの時の挙動変更

img2str.py
「正しい」戦利品のスクショではないときに quest_list がなくて正常終了しないエラーに対応
=> quest_list がないというエラーに対応

fgosccalc.py, img2str.py
- 所持アイテム一覧のデータを読んで周回前画像の未ドロップ数を補完する機能を追加 (-o, --owned オプション)  なお、所持数が0個の場合は対応していない
- lint エラーを修正
=> Material read add

fgosccalc.py
入力ファイルを与える順番がスクロール下→上の順序のときアイテムが重複表示されるバグを楸瑛
=> fix duplicate bug

dropitemseditor.py, img2str.py
画像で誤認識が発生したときに "" を取得すると ValueError を出して止まってしまう問題を修正
https://twitter.com/modeconverter/status/1293162935439593472
をcalctweet.pyで読み込んだときに発生
```
$ python calctweet.py -u https://twitter.com/modeconverter/status/1293162935439593472
Traceback (most recent call last):
File "calctweet.py", line 387, in <module>
get_one_tweet(args, api)
File "calctweet.py", line 270, in get_one_tweet
image_items, error_dic = calc_iamge_diff(status, savelocal=args.savelocal, debug=args.debug)
File "calctweet.py", line 134, in calc_iamge_diff
sc = img2str.ScreenShot(image, svm, dropitems, debug)
File "C:\Users\nono_000\Documents\git\dev9\fgosccalc\img2str.py", line 205, in __init__
item = Item(item_img_rgb, item_img_hsv, item_img_gray, svm,
File "C:\Users\nono_000\Documents\git\dev9\fgosccalc\img2str.py", line …
```
=> fix ValueError in ocr_digit()

img2str.py
phashだけだと2ゾロダイスを3ゾロダイスを誤認識するので専用の判別ルーチンを作成
=> 2ゾロダイス判別ルーチンの追加

static/js/src/report.jsx
Sentry はエラーレポート集約サービスで、ロードできなくてもサービスの提供に支障はない。
よって、ライブラリがロードできなかった場合は初期化処理を実行しない。
=> ブラウザ拡張により Sentry (全体の動作には非必須) が無効化された場合でもエラーで落ちないようにする。

.github/workflows/deploy.yml
item ディレクトリがない場合にプログラムが自動的に item ディレクトリを作ろうとして (app engine 環境下において) OSError が発生する。デプロイ前に先に item ディレクトリを作っておくことでこれを回避する。
=> github workflow 修正

dropitemseditor.py, fgosccalc.py, main.py
・複数ファイル認識時、スクロール上下のファイル認識順が周回前後で異なるとエラーになるバグ修正
周回後のアイテム情報を参考に認識処理を高速化する部分は無効とした
これはヒストグラム計算が遅かった時に導入したもので、今はおそらくそれほど速度は変わらないと思われる
・複数ファイル認識時アイテムがちゃんとマージされてなかった問題を修正
=> Sc merge fix

.github/workflows/deploy.yml
Cloud Build に入る前に、Cloud Storage 上のコンテナイメージが置かれるディレクトリを cleanup する。
=> Deploy: コンテナイメージのキャッシュの残り方が中途半端な場合にCloud Buildが失敗する問題の回避策。

.github/workflows/appengine.yml
`deploy` -> `Deploy To App Engine`
=> デプロイ先が複数になったので、わかりやすいように旧デプロイの名前を変える。

static/js/src/report.jsx
以前 #70 で Tweet に埋め込む URL を固定するようにしたが、完全移行が達成された現在、その意義はなくなっている。一方で、最新環境である Cloud Run 環境からの投稿であっても fgosccalc.appspot.com が挿入されるという問題が生じている。
Tweet URL を固定しないことで、それぞれの実行環境のドメインが挿入されるようになることを期待する。
=> Tweet URL の固定をやめる。

.github/workflows/cloudrun_prod.yml, .github/workflows/cloudrun_stg.yml
残す世代を一定数に保つことで Cloud storage の容量圧迫を防止する。
=> デプロイ時に、同時に古い世代の cloud run revision および container image を削除する。

static/js/src/report.jsx
prefix/suffix によるマッチングが不可能なので、対象クエスト名との完全一致で判定。
=> 追加ドロップ率の表記に対応。

static/js/src/report.jsx
fixes https://twitter.com/shoppo_fgo/status/1439850659705094146
=> (x3) を手入力してから直接入力に移行すると (x3) が削除される問題を修正。

img2str.py
現在のWEB版の仕様では、立ち上がったコンテナを他の人も使いまわすので他人が作った認識できないアイテムが影響しておかしなことがおこるためほとんど使用していないlocalからの読み込み機能を停止する
=> item画像のlocalからの読み込みをしないように

.github/workflows/cloudrun_prod.yml, .github/workflows/cloudrun_stg.yml, Dockerfile
いくつか warnings が出ていたので、それに従い必要な修正を実施。
- 依存する actions のリビジョンを `@master` `@main` (unstable) でなく `@v0` (stable) にする
- gcloud の認証を Service Account Key ではなく Workload Identity Federation にする
- https://github.com/google-github-actions/setup-gcloud#workload-identity-federation-preferred
=> update deploy actions

static/js/src/report.jsx
=> 先頭行のアイテムが !逆鱗 のように ! で開始する場合に最終出力が正しく出ない不具合を修正。

static/js/src/report.jsx
=> 妖精騎士杯メダルのx3変換は無効にする。

static/js/src/report.jsx
=> ドロップ率上昇の対象素材リストを更新

poetry.lock, pyproject.toml, requirements-docker.txt
#195 は OpenCV/Numpy のバージョンアップが含まれていたためマージが進まなかった。
今回は上記ライブラリのバージョンは固定し、他のみを更新。
=> update python dependencies without opencv/numpy
